apiVersion: v1
kind: Pod
metadata:
  name: nginx-postgres
  namespace: rinor
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    envFrom:
      - configMapRef:
          name: game-demo
    ports:
    - containerPort: 80
  - name: postgres
    image: postgres
    envFrom:
      - configMapRef:
          name: game-demo
      - secretRef:
          name: postgres-secret   
    ports:
    - containerPort: 5432